In [1]:
#Creating NumPy Arrays

import numpy as np

In [2]:
# Creating arrays

arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.zeros((3, 3))
#arr3 = np.ones((2, 4))
arr3 = np.arange(8).reshape(2, 4)
arr4 = np.arange(0, 10, 2)

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr3.T)

[1 2 3 4 5 6]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 1 2 3]
 [4 5 6 7]]
[0 2 4 6 8]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [3]:
#Array Attributes and Methods

print(arr1.ndim)   # Output: 1
print(arr2.shape)  # Output: (3, 3)
print(arr3.dtype)  # Output: float64
print(arr4.size)   # Output: 5
print(arr1)
arr5 = arr1.reshape(2, 3)
print(arr5)
print(arr5.ndim)
print(arr5.shape)

1
(3, 3)
int64
5
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [4]:
#Array Indexing and Slicing

print(arr3)

# Array indexing and slicing
print(arr1[0])        # Output: 1
print(arr3[1, 2])     # Output: 0.0
print(arr3[:, 1:3])   # Output: Slice rows, columns 1 to 2

[[0 1 2 3]
 [4 5 6 7]]
1
6
[[1 2]
 [5 6]]


In [5]:
# Array operations

arr6 = np.array([1, 2, 3])
arr7 = np.array([4, 5, 6])
print(arr6 + arr7)    # Output: [5 7 9]
print(arr6 * arr7)    # Output: [ 4 10 18]
print(np.dot(arr6, arr7))  # Output: Dot product

[5 7 9]
[ 4 10 18]
32


In [6]:
# Broadcasting

arr8 = np.array([[1, 2, 3], [4, 5, 6]])
arr9 = np.array([10, 20, 30])
print(arr8 + arr9)    # Output: [[11 22 33] [14 25 36]]

[[11 22 33]
 [14 25 36]]


In [7]:
# Array aggregation

arr10 = np.array([[1, 2], [3, 4]])
print(np.sum(arr10))      # Output: 10
print(np.mean(arr10))     # Output: 2.5
print(np.min(arr10))      # Output: 1
print(np.max(arr10))      # Output: 4

10
2.5
1
4


In [8]:
# Random number generation

rand_arr1 = np.random.rand(3)   # Generate random numbers between [0, 1)
rand_arr2 = np.random.randint(0, 100, 5)   # Generate random numbers from standard normal distribution
print(rand_arr1)
print(rand_arr2)

[0.40012715 0.17483203 0.44080216]
[63 97 34 65  6]


In [9]:
# Linear algebra operations

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print(np.matmul(mat1, mat2))   # Output: Matrix multiplication

[[19 22]
 [43 50]]


In [10]:
# Saving and loading arrays
arr10 = np.array([[1, 2], [3, 4]])
np.save('my_array.npy', arr10)   # Save array to file
loaded_arr = np.load('my_array.npy')   # Load array from file

SyntaxError: invalid syntax (182431802.py, line 2)